--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Shock95x/AuctionHouse
branches:
- master
projects:
  AuctionHouse:
    path: ""
    icon: icon.png
    libs:
    - src: poggit/libasynql/libasynql
      version: ^3.3.0
    - src: muqsit/InvMenu/InvMenu
      version: ^3.1.1
    - src: SOF3/await-generator/await-generator
      version: ^2.2.0
    - src: JackMD/UpdateNotifier/UpdateNotifier
      version: ^1.0.0
...